/*
 * Largely generated by NetBeans
 * But adapted to use the AbstractManager<T>
 * which was an idea I also got from Netbeans
 * the query getBookmarksForWeblog is 
 * from org.apache.roller.weblogger.pojos.WeblogBookmark.orm.xml
 */
package com.hkstlr.reeler.weblogger.weblogs.boundary.manager;

import com.hkstlr.reeler.app.boundary.manager.AbstractManager;
import com.hkstlr.reeler.weblogger.weblogs.entities.Weblog;
import com.hkstlr.reeler.weblogger.weblogs.entities.WeblogBookmark;
import java.util.List;
import java.util.logging.Logger;
import javax.ejb.Stateless;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

/**
 *
 * @author henry.kastler
 */
@Stateless
public class WeblogBookmarkManager extends AbstractManager<WeblogBookmark> {

    @Inject
    private Logger log;
    
    @PersistenceContext
    private EntityManager em;

    @Override
    protected EntityManager getEntityManager() {
        return em;
    }

    public WeblogBookmarkManager() {
        super(WeblogBookmark.class);
    }

    public List<WeblogBookmark> getBookmarksForWeblog(Weblog weblog) {
        String qlString = "SELECT b FROM WeblogBookmark b JOIN b.folder WHERE b.folder.weblog = ?1";
        Query query = getEntityManager().createQuery(qlString);
        query.setParameter(1, weblog);
        List<WeblogBookmark> results = query.getResultList();
        
        return results;
    }

}
